name: alfred CI

on:
  push:
    paths:
      - "alfred/**"
      - ".github/workflows/elixir-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: elixir:1.14
    defaults:
      run:
        working-directory: alfred
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt update
          apt install openssl git build-essential -y
          mix local.hex --force && mix local.rebar --force
          mix deps.get

      - name: Run linters and tests
        env:
          MIX_ENV: test
        run: mix ci
