---
name: cheapdeck CI

on:
  push:
    paths:
      - "cheapdeck/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12
    defaults:
      run:
        working-directory: cheapdeck

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          apt update && apt install -y build-essential curl bash
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run linters
        run: |
          uvx ruff format --check .
          uvx ruff check --output-format github .
