name: cheapdeck CI

on:
  push:
    paths:
      - "cheapdeck/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10.6-alpine
    defaults:
      run:
        working-directory: cheapdeck

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apk --update add build-base
        pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run linters
      run: |
        poetry run black --check .
        poetry run isort --check .
