---
name: cheapdeck CI

on:
  push:
    paths:
      - "cheapdeck/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12
    defaults:
      run:
        working-directory: cheapdeck

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        env:
          RYE_INSTALL_OPTION: "--yes"
        run: |
          apt update && apt install -y build-essential curl bash
          curl -sSf https://rye-up.com/get | bash
          . "$HOME/.rye/env"
          rye sync

      - name: Run linters
        run: |
          . "$HOME/.rye/env"
          rye format --check
          rye lint
